version: '3.7'

services:
  server:
    platform: linux/x86_64
    image: asia.gcr.io/aerial-studio-357602/server-service:1.8
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./src:/myfolder/src

  my-database:
    image: mysql:latest
    platform: linux/x86_64
    command:
      - --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: 'moyeo_server'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - 3306:3306

  redis:
    image: redis:latest
    ports:
      - 6379:6379
